version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    image: wahllywest/music-booking
    depends_on:
      - mongo