version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    image: wahllywest/music-booking
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodata:/mongodata/db
    ports:
      - '27017:27017'